apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qualitest.secretName" . }}
  labels:
    {{- include "qualitest.labels" . | nindent 4 }}
type: Opaque
stringData:
  TOKEN_SECRET: {{ .Values.secrets.tokenSecret | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  {{- if .Values.app.external.password }}
  EXTERNAL_MYSQL_PASSWORD: {{ .Values.app.external.password | quote }}
  {{- end }}
  {{- if .Values.app.external.redisPassword }}
  EXTERNAL_REDIS_PASSWORD: {{ .Values.app.external.redisPassword | quote }}
  {{- end }}
